[0m18:59:54.909130 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027263C37A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027261D04550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002726501FC50>]}


============================== 18:59:54.918721 | 5bb12b36-d945-4899-97e5-1e37b1e2c917 ==============================
[0m18:59:54.918721 [info ] [MainThread]: Running with dbt=1.10.4
[0m18:59:54.920152 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init telegram_dbt', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:59:54.959739 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\user\.dbt
[0m18:59:54.963739 [debug] [MainThread]: Starter project path: C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\include\starter_project
[0m18:59:55.013312 [info ] [MainThread]: 
Your new dbt project "telegram_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:59:55.014469 [info ] [MainThread]: Setting up your profile.
[0m19:02:43.596403 [info ] [MainThread]: Profile telegram_dbt written to C:\Users\user\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:02:43.601173 [debug] [MainThread]: Command `dbt init` succeeded at 19:02:43.600398 after 168.94 seconds
[0m19:02:43.603334 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272661E50F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000272661BED50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027264E77790>]}
[0m19:02:43.605471 [debug] [MainThread]: Flushing usage events
[0m19:02:44.629403 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:03:20.622578 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025E90787A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025E8E854550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025E91B83C50>]}


============================== 19:03:20.630163 | 7333f6d9-420e-4dfa-924b-1fd97a3c1f95 ==============================
[0m19:03:20.630163 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:03:20.631361 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m19:03:20.663852 [info ] [MainThread]: dbt version: 1.10.4
[0m19:03:20.664565 [info ] [MainThread]: python version: 3.13.5
[0m19:03:20.665105 [info ] [MainThread]: python path: C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Scripts\python.exe
[0m19:03:20.665561 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m19:03:20.747463 [info ] [MainThread]: Using profiles dir at C:\Users\user\.dbt
[0m19:03:20.748419 [info ] [MainThread]: Using profiles.yml file at C:\Users\user\.dbt\profiles.yml
[0m19:03:20.748993 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\user\Documents\Datasience\telegram-medical-insights\dbt\dbt_project.yml
[0m19:03:20.750452 [info ] [MainThread]: adapter type: postgres
[0m19:03:20.750977 [info ] [MainThread]: adapter version: 1.9.0
[0m19:03:20.751750 [info ] [MainThread]: Configuration:
[0m19:03:20.752347 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m19:03:20.752792 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m19:03:20.753206 [info ] [MainThread]: Required dependencies:
[0m19:03:20.753869 [debug] [MainThread]: Executing "git --help"
[0m19:03:20.812031 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m19:03:20.812600 [debug] [MainThread]: STDERR: "b''"
[0m19:03:20.813094 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m19:03:20.813755 [info ] [MainThread]: Connection:
[0m19:03:20.814291 [info ] [MainThread]:   host: db
[0m19:03:20.814741 [info ] [MainThread]:   port: 5432
[0m19:03:20.815155 [info ] [MainThread]:   user: postgres
[0m19:03:20.815603 [info ] [MainThread]:   database: telegram_data
[0m19:03:20.816019 [info ] [MainThread]:   schema: analytics_jane
[0m19:03:20.816400 [info ] [MainThread]:   connect_timeout: 10
[0m19:03:20.816788 [info ] [MainThread]:   role: None
[0m19:03:20.817156 [info ] [MainThread]:   search_path: None
[0m19:03:20.817520 [info ] [MainThread]:   keepalives_idle: 0
[0m19:03:20.817879 [info ] [MainThread]:   sslmode: None
[0m19:03:20.818225 [info ] [MainThread]:   sslcert: None
[0m19:03:20.818754 [info ] [MainThread]:   sslkey: None
[0m19:03:20.819310 [info ] [MainThread]:   sslrootcert: None
[0m19:03:20.819772 [info ] [MainThread]:   application_name: dbt
[0m19:03:20.820218 [info ] [MainThread]:   retries: 1
[0m19:03:20.820874 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m19:03:21.555383 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m19:03:28.219965 [debug] [MainThread]: Using postgres connection "debug"
[0m19:03:28.220949 [debug] [MainThread]: On debug: select 1 as id
[0m19:03:28.221538 [debug] [MainThread]: Opening a new connection, currently in state init
[0m19:03:30.917202 [error] [MainThread]: Encountered an error:

[0m19:03:31.144378 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\base\connections.py", line 237, in retry_connection
    connection.handle = connect()
                        ~~~~~~~^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\postgres\connections.py", line 144, in connect
    handle = psycopg2.connect(
        dbname=credentials.database,
    ...<5 lines>...
        **kwargs,
    )
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\cli\requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
                      ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\cli\requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\cli\main.py", line 420, in debug
    results = task.run()
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\task\debug.py", line 144, in run
    connection_status = self.test_connection()
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\task\debug.py", line 465, in test_connection
    connection_result = self.attempt_connection(self.profile)
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\task\debug.py", line 443, in attempt_connection
    adapter.debug_query()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\postgres\impl.py", line 157, in debug_query
    self.execute("select 1 as id")
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt_common\record.py", line 507, in record_replay_wrapper
    return func_to_record(*call_args, **kwargs)
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\base\impl.py", line 437, in execute
    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\sql\connections.py", line 219, in execute
    _, cursor = self.add_query(sql, auto_begin)
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\sql\connections.py", line 147, in add_query
    cursor = connection.handle.cursor()
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\contracts\connection.py", line 96, in handle
    self._handle.resolve(self)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\contracts\connection.py", line 120, in resolve
    return self.opener(connection)
           ~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\postgres\connections.py", line 176, in open
    return cls.retry_connection(
           ~~~~~~~~~~~~~~~~~~~~^
        connection,
        ^^^^^^^^^^^
    ...<4 lines>...
        retryable_exceptions=retryable_exceptions,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\adapters\base\connections.py", line 241, in retry_connection
    except tuple(retryable_exceptions) as e:
           ~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

[0m19:03:31.146713 [debug] [MainThread]: Command `dbt debug` failed at 19:03:31.146500 after 10.80 seconds
[0m19:03:31.147332 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m19:03:31.148410 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025E92C6F230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025E92DF6E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025E930E5480>]}
[0m19:03:31.149001 [debug] [MainThread]: Flushing usage events
[0m19:03:32.005261 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:28:50.619424 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000290305F7A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002902E6C4550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000290319E3C50>]}


============================== 19:28:50.623399 | 7d6743c4-ff3a-425a-a16c-b632aaf92774 ==============================
[0m19:28:50.623399 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:28:50.623984 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:28:50.640418 [info ] [MainThread]: dbt version: 1.10.4
[0m19:28:50.640931 [info ] [MainThread]: python version: 3.13.5
[0m19:28:50.641262 [info ] [MainThread]: python path: C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Scripts\python.exe
[0m19:28:50.641538 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m19:28:50.690787 [info ] [MainThread]: Using profiles dir at C:\Users\user\.dbt
[0m19:28:50.691552 [info ] [MainThread]: Using profiles.yml file at C:\Users\user\.dbt\profiles.yml
[0m19:28:50.692046 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\user\Documents\Datasience\telegram-medical-insights\dbt\dbt_project.yml
[0m19:28:50.693200 [info ] [MainThread]: adapter type: postgres
[0m19:28:50.693619 [info ] [MainThread]: adapter version: 1.9.0
[0m19:28:50.694079 [info ] [MainThread]: Configuration:
[0m19:28:50.694486 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m19:28:50.694908 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m19:28:50.695187 [info ] [MainThread]: Required dependencies:
[0m19:28:50.695453 [debug] [MainThread]: Executing "git --help"
[0m19:28:50.722544 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m19:28:50.722927 [debug] [MainThread]: STDERR: "b''"
[0m19:28:50.723230 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m19:28:50.723692 [info ] [MainThread]: Connection:
[0m19:28:50.724030 [info ] [MainThread]:   host: localhost
[0m19:28:50.724318 [info ] [MainThread]:   port: 5432
[0m19:28:50.724586 [info ] [MainThread]:   user: postgres
[0m19:28:50.724860 [info ] [MainThread]:   database: telegram_data
[0m19:28:50.725107 [info ] [MainThread]:   schema: analytics
[0m19:28:50.725349 [info ] [MainThread]:   connect_timeout: 10
[0m19:28:50.725593 [info ] [MainThread]:   role: None
[0m19:28:50.725828 [info ] [MainThread]:   search_path: None
[0m19:28:50.726061 [info ] [MainThread]:   keepalives_idle: 0
[0m19:28:50.726285 [info ] [MainThread]:   sslmode: None
[0m19:28:50.726532 [info ] [MainThread]:   sslcert: None
[0m19:28:50.726772 [info ] [MainThread]:   sslkey: None
[0m19:28:50.727086 [info ] [MainThread]:   sslrootcert: None
[0m19:28:50.727342 [info ] [MainThread]:   application_name: dbt
[0m19:28:50.727574 [info ] [MainThread]:   retries: 1
[0m19:28:50.727976 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m19:28:50.917676 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m19:28:50.973203 [debug] [MainThread]: Using postgres connection "debug"
[0m19:28:50.973550 [debug] [MainThread]: On debug: select 1 as id
[0m19:28:50.973768 [debug] [MainThread]: Opening a new connection, currently in state init
[0m19:28:55.085056 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

[0m19:28:59.174104 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m19:28:59.174591 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m19:28:59.174876 [debug] [MainThread]: On debug: No close available on handle
[0m19:28:59.175134 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m19:28:59.175668 [info ] [MainThread]: [31m2 checks failed:[0m
[0m19:28:59.176054 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\user\Documents\Datasience\telegram-medical-insights\dbt\dbt_project.yml> not found

[0m19:28:59.176440 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
  	Is the server running on that host and accepting TCP/IP connections?
  connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
  	Is the server running on that host and accepting TCP/IP connections?
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m19:28:59.178976 [debug] [MainThread]: Command `dbt debug` failed at 19:28:59.178857 after 8.74 seconds
[0m19:28:59.179270 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m19:28:59.179527 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029032ACF230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029032BC6450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029032A43CE0>]}
[0m19:28:59.179826 [debug] [MainThread]: Flushing usage events
[0m19:29:01.865067 [debug] [MainThread]: An error was encountered while trying to flush usage events
